# Start with a blank slate by unbinding everything
unbind-key -a -T prefix
unbind-key -a -T root
unbind-key -a -T copy-mode
unbind-key -a -T copy-mode-vi

# Set the prefix key
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Easily reload configuration changes
bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded."

# Start windows and panes at 1 instead of 0 and renumber when closed
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Add key bindings to split panes and open new panes in the current path
bind-key -T prefix b split-window -v -c "#{pane_current_path}"
bind-key -T prefix r split-window -h -c "#{pane_current_path}"

# Navigate panes using vim motions
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Zoom
bind-key z resize-pane -Z

### Adjust the keybindings to copy text from the terminal
##bind -T copy-mode-vi v send-keys -X begin-selection
##bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
##bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Increase history
set-option -g history-limit 5000
