# Start with a blank slate by unbinding everything
#unbind-key -a -T prefix
#unbind-key -a -T root
#unbind-key -a -T copy-mode
#unbind-key -a -T copy-mode-vi

# Set the prefix key
unbind-key C-b
unbind-key C-Space
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Easily reload configuration changes
unbind-key R
bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded."

# Start windows and panes at 1 instead of 0 and renumber when closed
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Add key bindings to split panes and open new panes in the current path
unbind-key b
unbind-key r
bind-key -T prefix b split-window -v -c "#{pane_current_path}"
bind-key -T prefix r split-window -h -c "#{pane_current_path}"

# Navigate panes using vim motions and the prefix key
unbind-key h
unbind-key j
unbind-key k
unbind-key l
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Navigate panes using vim motions without the prefix key
unbind-key C-h
unbind-key C-j
unbind-key C-k
unbind-key C-l
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

# Zoom
# bind-key z resize-pane -Z

# Adjust the keybindings to copy text from the terminal
#set-window-option -g mode-keys vi
##bind-key -n c copy-mode
#bind-key -T copy-mode-vi v send-keys -X begin-selection
#bind-key -T copy-mode-vi V send-keys -X select-line
#bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
#bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
#bind-key -T prefix p paste-buffer

# Increase history
set-option -g history-limit 5000
